name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        
  deploy-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          yourusername/document-chat-assistant:latest
          yourusername/document-chat-assistant:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  health-check:
    runs-on: ubuntu-latest
    needs: [deploy-vercel, deploy-docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for deployments
      run: sleep 60
      
    - name: Check Vercel deployment
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.VERCEL_URL }})
        if [ $response != "200" ]; then
          echo "Vercel deployment failed"
          exit 1
        fi
        
    - name: Check Docker deployment
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.DOCKER_URL }})
        if [ $response != "200" ]; then
          echo "Docker deployment failed"
          exit 1
        fi